# Generated by Django 5.2.1 on 2025-05-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movietable',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
