# Generated by Django 5.2.1 on 2025-05-29 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_movietable_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietable',
            name='user',
        ),
        migrations.CreateModel(
            name='MovieUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend_app.movietable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='backend_app.usertable')),
            ],
        ),
    ]
